### ISSUE TITLE
Sign transaction hash

### ISSUE THREAD

**Issue by bkbooth** [icon-project/ledger-app-icx#14]
Is there a way to sign a transaction hash using `ledger-app-icx`? It looks like it only supports signing raw ICON transaction strings.

Is there a way I could do it manually? Could support for signing transaction hashes be added?

My use case is being able to handle `REQUEST_SIGNING` requests from the [ICONex protocol](https://github.com/icon-project/iconex_chrome_extension/tree/master/docs/iconex_connect), and sign the transaction hash with a Ledger device.

**Comment by mksong76** [comment]
It's not allowed to get a signature without acknowledge of the operation.
For that reason, Ledger doesn't allow signing anonymous data without the user acknowledge.

**Comment by mj-hana** [comment]
@mksong-icon I think there is some misunderstanding. We want to extend the ledger-app-icx to be able to sign "personal messages" on a Ledger.

Below is an example with Bitcoin and Ledger, but you can also do with any private key. 
https://coinsutra.com/sign-message-ledger-wallet/

**Comment by mksong76** [comment]
I get what you want to do. But currently, we don't have any reason to implement those features for a specific purpose.

**Comment by mj-hana** [comment]
@mksong-icon The web auth module we built uses this method for authentication https://github.com/ReliantNode/django-icon-auth

It's currently being used on ICONpreps.com and we are using it for 2 other services in development.
