### ISSUE TITLE
Error when connecting to Ledger from ICONex Chrome extension ("Failed to connect")

### ISSUE THREAD

**Issue by plinkfuture** [icon-project/ledger-app-icx#2]
This continues to be a problem.  try to send a txn and if I don't immediately confirm the txn on my ledger as soon as it shows (not waiting to see the destination on my ledger) it doesn't record that I pressed the confirm button and times out and if I press it immediately - it gives the error "Failed to Connect."  I've tried it all ways from sunday, deleted chrome and extensions, reinstalled all, deleted AntiVirus all - had Ledger Wallets open, closed - makes no difference - So many people have this problem and theres no fix and no alternative for Ledger users.  MY ICON is stuck!!!  HELP

**Comment by couldseeme** [comment]
Thank you for reporting the issue.
Please update the ledger firmware and reinstall the ICON app. 
The latest version of ICON app is 1.0.3.
Let us know if the same issue persists.

**Comment by bz7593** [comment]
hi everyone i have probleme 
- i conect my ledger and i can open my iconex wallet
- but when i want to send transfer my icx i receive this message after pressing ok on my hardwar ledger
and the message is * Failed to connect. Please try again. * since 3 days i try ... can someone help ?? plz

**Comment by bz7593** [comment]
i install newb update thnk working

**Comment by cwkwak** [comment]
We are guessing this issue comes from between new chrome and ledger FW. So I think it will be resolved when you update ledger firmware.
New ledger FW update will cause removing all ledger apps, so you need to install ICON app again.
