### ISSUE TITLE
Error when confirming transactions on both Balanced and ICONEx through Ledger

### ISSUE THREAD

**Issue by GlenCurtisITT** [icon-project/ledger-app-icx#22]
Hi there, apologies if this is the wrong place but I can't seem to sign any transactions today through my Ledger.

When clicking confirm through my Ledger I get this error in the browser 
[RPC ERROR] SystemError: E2002:Expired(min-15m30.620033s)

This is happening on both Balanced and when sending transactions on ICONEx

My ledger is running on the most up to date firmware 2.1.0 and the ICX app is on 1.0.8

**Comment by sink772** [comment]
Hello @GlenCurtisITT,
`Expired(min-15m30.620033s)` means that your computer (or Ledger?) time is lagging compared to ICON nodes.
Please check it out first.
